services:
  - type: web
    name: chess-game
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y stockfish
      stockfish --version || echo "Stockfish not found"
      which stockfish || echo "Stockfish not in PATH"
      ls -l /usr/games/stockfish || echo "Not in /usr/games"
      ls -l /usr/bin/stockfish || echo "Not in /usr/bin"
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
